version: '2'

services:

  prometheus_srv:
    build: ./prom_serv
    image: prom/prometheus
    container_name: prometheus_server
    hostname: prometheus_server
    privileged: true
    # restart: always
    # command: /bin/bash
    # links:
      # - container_name
    # environment:
      # - DATABASE_NAME=dbname
    # ports:
      # - "8888:8888"
    # depends_on:
      # - container_name
 
  prometheus_node:
    image: prom/node-exporter
    container_name: prom_node_exporter
    hostname: prom_node_exporter
    privileged: true
    depends_on:
      - prometheus_srv

  prometheus_node2:
    image: prom/node-exporter
    container_name: prom_node_exporter2
    hostname: prom_node_exporter2
    privileged: true
    depends_on:
      - prometheus_srv

  grafana:
    image: grafana/grafana
    container_name: grafana_server
    hostname: grafana_server
    privileged: true
    depends_on:
      - prometheus_srv


